-- Central articles table

create table articles (
    id                       uuid primary key default gen_random_uuid(),
    source_adapter_id        uuid references source_adapters(id) on delete set null,
    ingestion_run_id         uuid references ingestion_runs(id) on delete set null,
    external_id              text,
    url                      text not null,
    canonical_url            text,
    url_hash                 text generated always as (encode(digest(url, 'sha256'), 'hex')) stored,
    title                    text not null,
    title_normalized         text,
    author                   text,
    byline                   text,
    outlet_id                uuid references outlets(id) on delete set null,
    outlet_name_raw          text,
    published_at             timestamptz,
    fetched_at               timestamptz not null default now(),
    body_snippet             text,
    language                 text not null default 'en',
    original_language        text,
    translated_title         text,
    translated_summary       text,
    translation_status       text check (translation_status in ('none', 'machine', 'manual')),
    region                   text,
    country                  text,
    channel                  channel_type not null default 'online',
    media_type               text,
    status                   article_status not null default 'pending',
    review_status            review_status,
    reviewed_by              uuid references profiles(id) on delete set null,
    reviewed_at              timestamptz,
    review_notes             text,
    is_paywalled             boolean not null default false,
    fulltext_status          fulltext_status not null default 'unavailable',
    is_syndicated            boolean not null default false,
    cluster_id               uuid,
    is_cluster_primary       boolean not null default false,
    priority_score           integer not null default 0,
    sentiment                text,
    ai_summary               text,
    ai_confidence            real,
    inclusion_rationale      text,
    exclusion_rationale      text,
    social_author_handle     text,
    social_display_name      text,
    social_follower_count    integer,
    social_engagement_metrics jsonb,
    social_is_sampled        boolean not null default false,
    metadata                 jsonb not null default '{}',
    created_at               timestamptz not null default now(),
    updated_at               timestamptz not null default now(),
    constraint articles_url_hash_unique unique (url_hash)
);
